blank_issues_enabled: false
contact_links:
  - name: Ask Questions & Community Discussions
    url: https://github.com/c250567/Subtitle/discussions
    about: Please ask questions and get help with SubtitleGo in GitHub Discussions.
  - name: Security Vulnerability Reporting
    url: https://github.com/c250567/Subtitle/security/advisories/new
    about: Privately report a security vulnerability to project maintainers.
